# Generated by Django 2.0.9 on 2018-12-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateslab',
            name='rate',
            field=models.IntegerField(),
        ),
    ]
