# Generated by Django 2.0.9 on 2018-12-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20181207_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwardorder',
            name='chamber',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=50),
        ),
    ]
