# Generated by Django 2.0.9 on 2018-12-14 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_inwardorder_chamber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inwardorder',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='outwardorder',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
