# Generated by Django 2.0.9 on 2018-12-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, max_length=20, verbose_name='Role of User'),
        ),
    ]
