# Generated by Django 2.0.9 on 2019-01-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20190102_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='firm',
            field=models.CharField(default='test', max_length=80),
            preserve_default=False,
        ),
    ]
