# Generated by Django 2.0.9 on 2018-12-07 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20181207_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='inward_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.InwardOrder'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='outward_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.OutwardOrder'),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice'),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='out_oli',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.OutOli'),
        ),
    ]
